---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create RSA key pair"
      vars:
        sec_key_ssh:
          setup: true
        sec_key_ssh_pairs:
          - file: "rsa-4096b"
            path: "/home/test/keys"
            owner: "test"
            group: "test"
            type: "rsa"
            size: "4096"
      ansible.builtin.include_role:
        name: "sec_key_ssh"
...
