---
- name: "Security / Key / SSH / Initialize"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_initialize.yml"

- name: "Security / Key / SSH / Setup"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_setup.yml"
  when:
    - "'setup' in sec_key_ssh"
    - sec_key_ssh['setup']

- name: "Security / Key / SSH / Finalize"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_finalize.yml"
...
