---
- name: "Security / Key / SSH / Setup / Pair / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - sec_key_ssh___pair['path'] is defined
      - sec_key_ssh___pair['path'] | length > 0
      - sec_key_ssh___pair['file'] is defined
      - sec_key_ssh___pair['file'] | length > 0
      - sec_key_ssh___pair['owner'] is defined
      - sec_key_ssh___pair['owner'] | length > 0
      - sec_key_ssh___pair['group'] is defined
      - sec_key_ssh___pair['group'] | length > 0

- name: "Security / Key / SSH / Setup / Pair / Create private/public SSH key ({{ sec_key_ssh___pair['file'] }}"
  become: true
  community.crypto.openssh_keypair:
    unsafe_writes: false
    force: false
    state: "present"
    regenerate: "full_idempotence"
    backend: "opensshbin"
    owner: "{{ sec_key_ssh___pair['owner'] }}"
    group: "{{ sec_key_ssh___pair['group'] }}"
    mode: "{{ sec_key_ssh_base['access']['mode']['file'] }}"
    path: "{{ sec_key_ssh___pair['path'] + '/' + sec_key_ssh___pair['file'] }}"
    type: "{{ sec_key_ssh___pair['type'] | default( omit ) }}"
    size: "{{ sec_key_ssh___pair['size'] | default( omit ) }}"
...
