---
- name: "Security / Key / SSH / Setup / Register / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - sec_key_ssh___knownhost['file'] is defined
      - sec_key_ssh___knownhost['file'] | length > 0
      - sec_key_ssh___knownhost['hosts'] is defined
      - sec_key_ssh___knownhost['hosts'] | length > 0
      - sec_key_ssh___knownhost['owner'] is defined
      - sec_key_ssh___knownhost['owner'] | length > 0
      - sec_key_ssh___knownhost['group'] is defined
      - sec_key_ssh___knownhost['group'] | length > 0

- name: "Security / Key / SSH / Setup / Register / Hosts"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_setup_register_hosts.yml"
  loop: "{{ sec_key_ssh___knownhost['hosts'] }}"
  loop_control:
    loop_var: "sec_key_ssh___host"
...
