---
- name: "Security / Key / SSH / Setup / Pair"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_setup_pair.yml"
  loop: "{{ sec_key_ssh_pairs }}"
  loop_control:
    loop_var: "sec_key_ssh___pair"
  when:
    - sec_key_ssh_pairs is defined
    - sec_key_ssh_pairs | length > 0

- name: "Security / Key / SSH / Setup / Remote"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_setup_remote.yml"
  loop: "{{ sec_key_ssh_remotes }}"
  loop_control:
    loop_var: "sec_key_ssh___target"
  when:
    - sec_key_ssh_remotes is defined
    - sec_key_ssh_remotes | length > 0

- name: "Security / Key / SSH / Setup / Register"
  ansible.builtin.include_tasks:
    file: "sec_key_ssh_setup_register.yml"
  loop: "{{ sec_key_ssh_knownhosts }}"
  loop_control:
    loop_var: "sec_key_ssh___knownhost"
  when:
    - sec_key_ssh_knownhosts is defined
    - sec_key_ssh_knownhosts | length > 0
...
