---
- name: "Security / Key / SSH / Setup / Register / Create known_hosts file ({{ sec_key_ssh___knownhost['file'] }})"
  become: true
  changed_when: false
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "touch"
    owner: "{{ sec_key_ssh___knownhost['owner'] }}"
    group: "{{ sec_key_ssh___knownhost['group'] }}"
    mode: "0600"
    path: "{{ sec_key_ssh___knownhost['file'] }}"

- name: "Security / Key / SSH / Setup / Register / Obtain remote host server key ({{ sec_key_ssh___host }})"
  ansible.builtin.command:
    argv:
      - "{{ sec_key_ssh_base['run']['ssh_keyscan'] }}"
      - "{{ sec_key_ssh___host }}"
  register: "sec_key_ssh___serverkeys"
  changed_when: false

- name: "Security / Key / SSH / Setup / Register / Register host in known_hosts file"
  become: true
  ansible.builtin.known_hosts:
    state: "present"
    name: "{{ sec_key_ssh___host }}"
    hash_host: "{{ sec_key_ssh___knownhost['hash'] | default( false ) }}"
    path: "{{ sec_key_ssh___knownhost['file'] }}"
    key: "{{ sec_key_ssh___serverkey }}"
  loop: "{{ sec_key_ssh___serverkeys['stdout_lines'] }}"
  loop_control:
    loop_var: "sec_key_ssh___serverkey"
...
