---
- name: "Security / OpenSSH / Client / Initialize"
  ansible.builtin.include_tasks:
    file: "sec_openssh_client_initialize.yml"

- name: "Security / OpenSSH / Client / Deploy"
  ansible.builtin.include_tasks:
    file: "sec_openssh_client_deploy.yml"
  when:
    - "'deploy' in sec_openssh_client"
    - sec_openssh_client['deploy']

- name: "Security / OpenSSH / Client / Finalize"
  ansible.builtin.include_tasks:
    file: "sec_openssh_client_finalize.yml"
...
