---
- name: "Security / OpenSSH / Client / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sec_openssh_client_application }}"
    sys_package_profiles: "{{ sec_openssh_client_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
