---
- name: "Security / OpenSSH / Client / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sec_openssh_client_platforms

- name: "Security / OpenSSH / Client / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "Security / OpenSSH / Client / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sec_openssh_client_prerequisite.yml"
  when:
    - "'resolve_prereq' in sec_openssh_client"
    - sec_openssh_client['resolve_prereq']
...
