---
- name: "Security / Firewall / OS / Provision / Rule / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Invalid rule definition: {{ sec_firewall_os___provision_rule }}"
    that:
      - sec_firewall_os___provision_rule['id'] is defined
      - sec_firewall_os___provision_rule['zone'] is defined
      - sec_firewall_os___provision_rule['allow'] is defined
      - (sec_firewall_os___provision_rule['service'] is defined or sec_firewall_os___provision_rule['port'] is defined)

- name: "Security / Firewall / OS / Provision / Rule / Add (id: {{ sec_firewall_os___provision_rule['id'] }})"
  become: true
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    offline: true
    zone: "{{ sec_firewall_os___provision_rule['zone'] }}"
    service: "{{ ( sec_firewall_os___provision_rule['service'] ) | default( omit ) }}"
    port: "{{ ( sec_firewall_os___provision_rule['port'] ) | default( omit ) }}"
    state: "{{ sec_firewall_os___provision_rule['allow'] | ternary( 'enabled', 'disabled' ) }}"
...
