---
- name: "Security / Firewall / OS / Control / Subsystem / Set state (service: {{ sec_firewall_os_subsystems['service'] }})"
  become: true
  ansible.builtin.systemd:
    no_block: false
    scope: "system"
    name: "{{ sec_firewall_os_subsystems['service'] }}"
    state: "{{
      sec_firewall_os_subsystems['states']
      [sec_firewall_os_subsystem['status']]
    }}"
...
