---
- name: "Security / OpenSSH / Server / Deploy / Options / Install XAuth support"
  vars:
    sys_package:
      provision: true
    sys_package_application:
      name: "xauth"
      type: "distro"
      version: "latest"
      installed: "{{ sec_openssh_server_application['installed'] }}"
    sys_package_profiles: "{{ sec_openssh_server_profiles['xauth'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
  when:
    - sec_openssh_server_options['xauth'] is defined
    - sec_openssh_server_options['xauth']
...
