---
- name: "Security / OpenSSH / Server / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sec_openssh_server_platforms

- name: "Security / OpenSSH / Server / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "platform-{{ sec_openssh_server_os_family }}.yml"

- name: "Security / OpenSSH / Server / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sec_openssh_server_prerequisite.yml"
  when:
    - "'resolve_prereq' in sec_openssh_server"
    - sec_openssh_server['resolve_prereq']
...
