---
sec_openssh_client_base:
  run:
    ssh_keygen: "/usr/bin/ssh-keygen"
    sshpass: "/usr/bin/sshpass"

sec_openssh_client_profiles:
  distro:
    latest:
      packages:
        - name: "openssh-client"
        - name: "sshpass"

sec_openssh_client_repository_catalog_distro: {}
...
