---
- name: "Security / Firewall / OS / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install, setup and start os firewall"
      vars:
        sec_firewall_os:
          resolve_prereq: true
          deploy: true
          setup: true
          provision: true
          control: true
        sec_firewall_os_subsystem:
          enabled: true
          status: "started"
        sec_firewall_os_rules:
          - id: "ssh_allow"
            zone: "public"
            service: "ssh"
            allow: true
      ansible.builtin.include_role:
        name: "serdigital64.security.sec_firewall_os"
...
