---
- name: "Security / OpenSSH / Client / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install distro native OpenSSH client package"
      vars:
        sec_openssh_client:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.security.sec_openssh_client"
...
